services:
  web:
    build: .
    command: gunicorn MedEase.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=localhost,127.0.0.1,medease-production.up.railway.app

# Tidak ada layanan db karena menggunakan NeonDB