# Generated by Django 4.2.16 on 2024-12-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='package_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('1day', '1 Day'), ('3day', '3 Days'), ('7day', '7 Days')], max_length=10),
        ),
    ]
