# Generated by Django 4.2.16 on 2024-12-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('specialty', models.CharField(max_length=100, verbose_name='Spesialisasi')),
                ('gender', models.CharField(choices=[('M', 'Laki-laki'), ('F', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('rate', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Rating')),
                ('fee_per_session', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Biaya per Sesi')),
                ('profile_picture', models.ImageField(upload_to='doctors/', verbose_name='Foto Profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dokter',
                'verbose_name_plural': 'Dokter',
                'ordering': ['name'],
            },
        ),
    ]
