# Generated by Django 4.2.16 on 2024-12-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi'),
        ),
    ]
